name: "Deploy to prod"

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: "osc-fr1"
      url: https://test-sample-gha.osc-fr1.scalingo.io/
    steps:
      - name: Install Scalingo CLI
        run: curl -O https://cli-dl.scalingo.com/install && bash install
      - name: Authenticating to Scalingo
        run: scalingo login --api-token ${{secrets.SCALINGO_API_TOKEN}}
      - name: Deploying to Scalingo
        run: scalingo --region ${{vars.SCALINGO_REGION}} --app ${{vars.SCALINGO_APP}} integration-link-manual-deploy -f ${{github.ref_name}}
